### ISSUE TITLE
Entrega-Modulo-3-Tarea-01-Divisas

### ISSUE THREAD

**Issue by abenitez74** [academia-geek/aprendices-geek-entrenamiento-abenitez74#1]
![image](https://user-images.githubusercontent.com/17518855/148232230-fc3438f7-e6da-43b6-8f5f-71a61af0d95c.png)

![image](https://user-images.githubusercontent.com/17518855/148232296-6b4c8cf1-043d-476a-835c-28b9180b10b9.png)
![image](https://user-images.githubusercontent.com/17518855/148232332-4a5afc51-0bbd-4f88-abb1-a13ffa249f7d.png)
![image](https://user-images.githubusercontent.com/17518855/148232390-0121da79-7d02-4658-9fb7-6b0820b16523.png)
# Desarrollo Ejercicio

Para dar solución al ejercicio, se crea la siguiente estructura:

![image](https://user-images.githubusercontent.com/17518855/148232655-d78e44fd-2f66-495d-a89c-ee95b41de640.png)

En el css, se le aplican los estilos para que quede similar al ejercicio, se crea un archivo js en el cual estan las funciones encargadas de cargar desde javascript los elementos del array que tendran los select en html.

Se crea una funcion validar en la cual se valida si la entrada del input es numerico o diferente de un numero con la funcion isNaN.

Se crea otra funcion llamada convertir la cual es la encargada de ejecutar la conversion de acuerdo a los valores de los select y que luego por medio de estructuras de decision IF determina el resultado.

**Comment by jennymontoya1001** [comment]
Buenas tardes @abenitez74, espero te encuentres muy bien. Buenas tardes @DavidCharif, espero te encuentres muy bien. Por favor relaciona la URL del repositorio en donde se encuentra el código y la URL de despliegue. Recuerda etiquetar a  @JohnFlorez25. Saludos

**Comment by abenitez74** [comment]
URL Repositorio: https://github.com/abenitez74/Geek-conversor-moneda
URL Despliegue: https://abenitez74.github.io/Geek-conversor-moneda/

**Comment by jennymontoya1001** [comment]
Buenas tardes @abenitez74 , espero te encuentres muy bien. Tu reto cumple con los requisitos solicitados. Observación: Ten en cuenta para este reto y los próximos que el código de los ejercicios, debe estar en el mismo campo de entrenamiento en la carpeta correspondiente, por ejemplo para este reto sería la siguiente ruta https://github.com/academia-geek/aprendices-geek-entrenamiento-abenitez74/tree/master/Modulo-3/Tarea-01. Éxitos.
